#! /bin/bash

file="text.txt"

#requires youtube-dl & mpv

while read -r line; do

	if [[ $line == *"no"* ]]; then

		echo "starting playlist"

		mpv --no-video 'https://www.youtube.com/watch?v=IMpNJ_sXVhU'
		mpv --no-video 'https://www.youtube.com/watch?v=WgTMeICssXY'
		mpv --no-video 'https://www.youtube.com/watch?v=jcq5NlYz1PU'
		mpv --no-video 'https://www.youtube.com/watch?v=zUHxBpofA1Y&list=RDnZowoM3Y9mg&index=27' 
		mpv --no-video 'https://www.youtube.com/watch?v=MivnLGwz_PA' 
		mpv --no-video 'https://www.youtube.com/watch?v=1FLkth-OnUQ'
		mpv --no-video 'https://www.youtube.com/watch?v=vtmVhEd9teM'
		mpv --no-video 'https://www.youtube.com/watch?v=rhKxdVIXFSo' 
		mpv --no-video 'https://www.youtube.com/watch?v=mF21khnuNPw'
		mpv --no-video 'https://www.youtube.com/watch?v=Dc_u4DHExj4'
		mpv --no-video 'https://www.youtube.com/watch?v=gM7Hlg75Mlo'
		mpv --no-video 'https://www.youtube.com/watch?v=wEERFBI9eCg'
		mpv --no-video 'https://www.youtube.com/watch?v=pjTj-_55WZ8'
		mpv --no-video 'https://www.youtube.com/watch?v=qFPHtXvHRSE'
		mpv --no-video 'https://www.youtube.com/watch?v=_eQQKVKjifQ'
		mpv --no-video 'https://www.youtube.com/watch?v=ryNQK_5EqCo'
		mpv --no-video 'https://www.youtube.com/watch?v=42TI-mP2Ss4'
		mpv --no-video 'https://www.youtube.com/watch?v=v7hCLkoMK_U&list=RDoTwVce9eWb4&index=9'
		mpv --no-video 'https://www.youtube.com/watch?v=wMykYSQaG_c'
		mpv --no-video 'https://www.youtube.com/watch?v=ZEuy1QnxKOk'
		mpv --no-video 'https://www.youtube.com/watch?v=HGmjkiXWDJM'
		mpv --no-video 'https://www.youtube.com/watch?v=IMpNJ_sXVhU'
		mpv --no-video 'https://www.youtube.com/watch?v=sOdbUhAwGcA'
		mpv --no-video 'https://www.youtube.com/watch?v=j6Keg3XKKjM'
		mpv --no-video 'https://www.youtube.com/watch?v=2LjeGA071xE'
		mpv --no-video 'https://www.youtube.com/watch?v=9l4YS4h1VqA'
		mpv --no-video 'https://www.youtube.com/watch?v=Tn-qE-h7s84'
		mpv --no-video 'https://www.youtube.com/watch?v=0gcNehB-YHI'
		mpv --no-video 'https://www.youtube.com/watch?v=oIhNoeKFwbE'
		mpv --no-video 'https://www.youtube.com/watch?v=EFEmTsfFL5A'
		mpv --no-video 'https://www.youtube.com/watch?v=ycaClKQeq1k'
		mpv --no-video 'https://www.youtube.com/watch?v=VOQtB0xTiek'
		mpv --no-video 'https://www.youtube.com/watch?v=o_kPzjTL4wQ'
		mpv --no-video 'https://www.youtube.com/watch?v=0VAAS9xnS5U'
		mpv --no-video 'https://www.youtube.com/watch?v=0j3SI7FRJVk'
		mpv --no-video 'https://www.youtube.com/watch?v=B8aH4cRdplE'
		mpv --no-video 'https://www.youtube.com/watch?v=wuISuoukZU0'
		mpv --no-video 'https://www.youtube.com/watch?v=bX-obw7vqSw'
		mpv --no-video 'https://www.youtube.com/watch?v=FPwLlpAfTOk'
		mpv --no-video 'https://www.youtube.com/watch?v=6mSpAFATxME'
		mpv --no-video 'https://www.youtube.com/watch?v=iHW95x9HnY0'
		mpv --no-video 'https://www.youtube.com/watch?v=jUjd6DHAutU'
		mpv --no-video 'https://www.youtube.com/watch?v=nwLz_PJEiVE'
#
		mpv --no-video 'https://www.youtube.com/watch?v=q1avmXtq0C0'
		mpv --no-video 'https://www.youtube.com/watch?v=AwlkfJHtmVk'
		mpv --no-video 'https://www.youtube.com/watch?v=Y4EE_aO7-1w'
		mpv --no-video 'https://www.youtube.com/watch?v=zIKS_U5lRL0'
		mpv --no-video 'https://www.youtube.com/watch?v=CEP6ta5SF8I'
		mpv --no-video 'https://www.youtube.com/watch?v=VFPhEn6ifV0'

	elif [[ $line == *"yes"* ]]; then
		
                echo "starting playlist"

                mpv 'https://www.youtube.com/watch?v=IMpNJ_sXVhU'
                mpv 'https://www.youtube.com/watch?v=WgTMeICssXY'
                mpv 'https://www.youtube.com/watch?v=jcq5NlYz1PU'
                mpv 'https://www.youtube.com/watch?v=zUHxBpofA1Y&list=RDnZowoM3Y9mg&index=27' 
                mpv 'https://www.youtube.com/watch?v=MivnLGwz_PA' 
                mpv 'https://www.youtube.com/watch?v=1FLkth-OnUQ'
                mpv 'https://www.youtube.com/watch?v=vtmVhEd9teM'
                mpv 'https://www.youtube.com/watch?v=rhKxdVIXFSo' 
                mpv 'https://www.youtube.com/watch?v=mF21khnuNPw'
                mpv 'https://www.youtube.com/watch?v=Dc_u4DHExj4'
                mpv 'https://www.youtube.com/watch?v=gM7Hlg75Mlo'
                mpv 'https://www.youtube.com/watch?v=wEERFBI9eCg'
                mpv 'https://www.youtube.com/watch?v=pjTj-_55WZ8'
                mpv 'https://www.youtube.com/watch?v=qFPHtXvHRSE'
                mpv 'https://www.youtube.com/watch?v=_eQQKVKjifQ'
                mpv 'https://www.youtube.com/watch?v=ryNQK_5EqCo'
                mpv 'https://www.youtube.com/watch?v=42TI-mP2Ss4'
                mpv 'https://www.youtube.com/watch?v=v7hCLkoMK_U&list=RDoTwVce9eWb4&index=9'
                mpv 'https://www.youtube.com/watch?v=wMykYSQaG_c'
                mpv 'https://www.youtube.com/watch?v=ZEuy1QnxKOk'
                mpv 'https://www.youtube.com/watch?v=HGmjkiXWDJM'
                mpv 'https://www.youtube.com/watch?v=IMpNJ_sXVhU'
                mpv 'https://www.youtube.com/watch?v=sOdbUhAwGcA'
                mpv 'https://www.youtube.com/watch?v=j6Keg3XKKjM'
                mpv 'https://www.youtube.com/watch?v=2LjeGA071xE'
                mpv 'https://www.youtube.com/watch?v=9l4YS4h1VqA'
                mpv 'https://www.youtube.com/watch?v=Tn-qE-h7s84'
                mpv 'https://www.youtube.com/watch?v=0gcNehB-YHI'
                mpv 'https://www.youtube.com/watch?v=oIhNoeKFwbE'
                mpv 'https://www.youtube.com/watch?v=EFEmTsfFL5A'
                mpv 'https://www.youtube.com/watch?v=ycaClKQeq1k'
                mpv 'https://www.youtube.com/watch?v=VOQtB0xTiek'
                mpv 'https://www.youtube.com/watch?v=o_kPzjTL4wQ'
                mpv 'https://www.youtube.com/watch?v=0VAAS9xnS5U'
                mpv 'https://www.youtube.com/watch?v=0j3SI7FRJVk'
                mpv 'https://www.youtube.com/watch?v=B8aH4cRdplE'
                mpv 'https://www.youtube.com/watch?v=wuISuoukZU0'
                mpv 'https://www.youtube.com/watch?v=bX-obw7vqSw'
                mpv 'https://www.youtube.com/watch?v=FPwLlpAfTOk'
                mpv 'https://www.youtube.com/watch?v=6mSpAFATxME'
                mpv 'https://www.youtube.com/watch?v=iHW95x9HnY0'
                mpv 'https://www.youtube.com/watch?v=jUjd6DHAutU'
                mpv 'https://www.youtube.com/watch?v=nwLz_PJEiVE'

		mpv 'https://www.youtube.com/watch?v=q1avmXtq0C0'
                mpv 'https://www.youtube.com/watch?v=AwlkfJHtmVk'
                mpv 'https://www.youtube.com/watch?v=Y4EE_aO7-1w'
                mpv 'https://www.youtube.com/watch?v=zIKS_U5lRL0'
                mpv 'https://www.youtube.com/watch?v=CEP6ta5SF8I'
                mpv 'https://www.youtube.com/watch?v=VFPhEn6ifV0'
	fi
done < $file

# Note: I don't own this music and this project is just something fun I did to get a better understanding of bash scripting, I might expand on this later
